### ISSUE TITLE
Servidor solo recibe 100 imágenes

### ISSUE THREAD

**Issue by kevv87** [Pablouc/serversEvaluator#7]
Actualmente el servidor deja de recibir imágenes después de que el contador de server.c alcanza las 100 imágenes recibidas.

No debería ser así, según la especificación el servidor debería guardar solo las primeras 100 imágenes recibidas, pero debe procesar la cantidad de imágenes que se le envíe desde el cliente.

Creo que para arreglar esto podríamos crear un archivo temporal único para cada hilo/proceso que va a manejar una imagen. Este archivo temporal lo sobreescibimos cada vez que un hilo va a empezar a volver a escribir la información de una nueva imagen y lo borramos cuando muera el hilo/proceso.

**Comment by Guitarrunner** [comment]
Issue resuelto, imagenes extra se guardan en la carpeta temporal para no consumir espacio

**Comment by Guitarrunner** [comment]
Done
